
# this file defines a pipeline, a set of rules for building and validating the source code in a repo
# it's written in a format called YAML

# trigger defined when the pipeline will run.
# list-of-branches syntax:
# trigger:
# - main

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .
# short for "agent pool" as in "build agent"
# i.e.: what set of machines will be the build agents to run these steps.
pool:
  vmImage: ubuntu-latest


# variables common to multiple steps
variables:
  sdkVersion: 3.1.x
  buildConfiguration: Release

#these steps are run in sequence by the build agent.
# in a directory that contains the most recent push on that repo.
steps:
# the two most common types of steps are "script" and "task"
- task: UseDotNet@2
  displayName: dotnet sdk 2.x
  inputs:
    packageType: 'sdk'
    version: '2.x'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Devop'
    organization: '2011-nov02-net'
    scannerMode: 'MSBuild'
    projectKey: '2011-nov02-net_Jordan-Project-01'
    projectName: 'StoreApp'
#- task: UseDotNet@2
#  displayName: dotnet sdk $(sdkVersion)
#  inputs:
#    packageType: 'sdk'
#
#    version: '$(sdkVersion)'
- task: UseDotNet@2
  displayName: 'Use .NET 5 SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.cproj'
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: dotnet build

- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: sonar analysis publish
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: dotnet test2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: -o testpath

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  displayName: dotnet publish

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(df6ff56e-adce-469a-8485-54a817a8762b)'
    appType: 'webApp'
    WebAppName: 'Garcia-OrderApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'